"""Initial schema with all racing tables

Revision ID: 687bc6da7b05
Revises: 
Create Date: 2026-02-07 01:11:44.635617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687bc6da7b05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('sire_name', sa.String(length=100), nullable=True),
    sa.Column('dam_name', sa.String(length=100), nullable=True),
    sa.Column('dam_sire_name', sa.String(length=100), nullable=True),
    sa.Column('breeder_name', sa.String(length=200), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horses')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_horses_name'), 'horses', ['name'], unique=False, schema='racing')
    op.create_index(op.f('ix_racing_horses_registration_number'), 'horses', ['registration_number'], unique=True, schema='racing')
    op.create_table('jockeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jockeys')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_jockeys_api_id'), 'jockeys', ['api_id'], unique=True, schema='racing')
    op.create_index(op.f('ix_racing_jockeys_last_name'), 'jockeys', ['last_name'], unique=False, schema='racing')
    op.create_table('owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_owners_name'), 'owners', ['name'], unique=False, schema='racing')
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(length=10), nullable=False),
    sa.Column('track_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_tracks_track_id'), 'tracks', ['track_id'], unique=True, schema='racing')
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_trainers_api_id'), 'trainers', ['api_id'], unique=True, schema='racing')
    op.create_index(op.f('ix_racing_trainers_last_name'), 'trainers', ['last_name'], unique=False, schema='racing')
    op.create_table('horse_owners',
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['racing.horses.id'], name=op.f('fk_horse_owners_horse_id_horses')),
    sa.ForeignKeyConstraint(['owner_id'], ['racing.owners.id'], name=op.f('fk_horse_owners_owner_id_owners')),
    sa.PrimaryKeyConstraint('horse_id', 'owner_id', name=op.f('pk_horse_owners')),
    schema='racing'
    )
    op.create_table('meets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meet_id', sa.String(length=50), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['racing.tracks.id'], name=op.f('fk_meets_track_id_tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meets')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_meets_date'), 'meets', ['date'], unique=False, schema='racing')
    op.create_index(op.f('ix_racing_meets_meet_id'), 'meets', ['meet_id'], unique=True, schema='racing')
    op.create_table('races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=200), nullable=True),
    sa.Column('post_time', sa.String(length=20), nullable=True),
    sa.Column('post_time_dt', sa.DateTime(), nullable=True),
    sa.Column('off_time', sa.Integer(), nullable=True),
    sa.Column('distance_value', sa.Integer(), nullable=True),
    sa.Column('distance_unit', sa.String(length=20), nullable=True),
    sa.Column('distance_description', sa.String(length=50), nullable=True),
    sa.Column('surface', sa.Enum('DIRT', 'TURF', 'SYNTHETIC', 'UNKNOWN', name='surfacetype'), nullable=True),
    sa.Column('surface_description', sa.String(length=50), nullable=True),
    sa.Column('track_condition', sa.String(length=50), nullable=True),
    sa.Column('race_type', sa.Enum('MAIDEN', 'CLAIMING', 'ALLOWANCE', 'STAKES', 'HANDICAP', 'UNKNOWN', name='racetype'), nullable=True),
    sa.Column('race_type_description', sa.String(length=100), nullable=True),
    sa.Column('race_class', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('age_restriction', sa.String(length=50), nullable=True),
    sa.Column('sex_restriction', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('min_claim_price', sa.Integer(), nullable=True),
    sa.Column('max_claim_price', sa.Integer(), nullable=True),
    sa.Column('purse', sa.Integer(), nullable=True),
    sa.Column('has_finished', sa.Boolean(), nullable=True),
    sa.Column('has_results', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meet_id'], ['racing.meets.id'], name=op.f('fk_races_meet_id_meets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_races_meet_id'), 'races', ['meet_id'], unique=False, schema='racing')
    op.create_table('payoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('wager_type', sa.String(length=10), nullable=False),
    sa.Column('wager_name', sa.String(length=50), nullable=True),
    sa.Column('winning_numbers', sa.String(length=50), nullable=True),
    sa.Column('base_amount', sa.Float(), nullable=True),
    sa.Column('payoff_amount', sa.Float(), nullable=True),
    sa.Column('total_pool', sa.Float(), nullable=True),
    sa.Column('number_of_winning_tickets', sa.Integer(), nullable=True),
    sa.Column('carryover', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['racing.races.id'], name=op.f('fk_payoffs_race_id_races')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payoffs')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_payoffs_race_id'), 'payoffs', ['race_id'], unique=False, schema='racing')
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('fractional_times', sa.JSON(), nullable=True),
    sa.Column('winning_time_seconds', sa.Float(), nullable=True),
    sa.Column('also_ran', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['racing.races.id'], name=op.f('fk_race_results_race_id_races')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_results')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_race_results_race_id'), 'race_results', ['race_id'], unique=True, schema='racing')
    op.create_table('runners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('jockey_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('program_number', sa.String(length=10), nullable=False),
    sa.Column('program_number_stripped', sa.Integer(), nullable=True),
    sa.Column('post_position', sa.String(length=10), nullable=True),
    sa.Column('morning_line_odds', sa.String(length=20), nullable=True),
    sa.Column('morning_line_decimal', sa.Float(), nullable=True),
    sa.Column('live_odds', sa.String(length=20), nullable=True),
    sa.Column('live_odds_decimal', sa.Float(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('claiming_price', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('medication', sa.String(length=50), nullable=True),
    sa.Column('is_scratched', sa.Boolean(), nullable=True),
    sa.Column('is_coupled', sa.Boolean(), nullable=True),
    sa.Column('scratch_indicator', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['racing.horses.id'], name=op.f('fk_runners_horse_id_horses')),
    sa.ForeignKeyConstraint(['jockey_id'], ['racing.jockeys.id'], name=op.f('fk_runners_jockey_id_jockeys')),
    sa.ForeignKeyConstraint(['race_id'], ['racing.races.id'], name=op.f('fk_runners_race_id_races')),
    sa.ForeignKeyConstraint(['trainer_id'], ['racing.trainers.id'], name=op.f('fk_runners_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runners')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_runners_horse_id'), 'runners', ['horse_id'], unique=False, schema='racing')
    op.create_index(op.f('ix_racing_runners_jockey_id'), 'runners', ['jockey_id'], unique=False, schema='racing')
    op.create_index(op.f('ix_racing_runners_race_id'), 'runners', ['race_id'], unique=False, schema='racing')
    op.create_index(op.f('ix_racing_runners_trainer_id'), 'runners', ['trainer_id'], unique=False, schema='racing')
    op.create_table('runner_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('race_result_id', sa.Integer(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('win_payoff', sa.Float(), nullable=True),
    sa.Column('place_payoff', sa.Float(), nullable=True),
    sa.Column('show_payoff', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_result_id'], ['racing.race_results.id'], name=op.f('fk_runner_results_race_result_id_race_results')),
    sa.ForeignKeyConstraint(['runner_id'], ['racing.runners.id'], name=op.f('fk_runner_results_runner_id_runners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_results')),
    schema='racing'
    )
    op.create_index(op.f('ix_racing_runner_results_race_result_id'), 'runner_results', ['race_result_id'], unique=False, schema='racing')
    op.create_index(op.f('ix_racing_runner_results_runner_id'), 'runner_results', ['runner_id'], unique=True, schema='racing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_racing_runner_results_runner_id'), table_name='runner_results', schema='racing')
    op.drop_index(op.f('ix_racing_runner_results_race_result_id'), table_name='runner_results', schema='racing')
    op.drop_table('runner_results', schema='racing')
    op.drop_index(op.f('ix_racing_runners_trainer_id'), table_name='runners', schema='racing')
    op.drop_index(op.f('ix_racing_runners_race_id'), table_name='runners', schema='racing')
    op.drop_index(op.f('ix_racing_runners_jockey_id'), table_name='runners', schema='racing')
    op.drop_index(op.f('ix_racing_runners_horse_id'), table_name='runners', schema='racing')
    op.drop_table('runners', schema='racing')
    op.drop_index(op.f('ix_racing_race_results_race_id'), table_name='race_results', schema='racing')
    op.drop_table('race_results', schema='racing')
    op.drop_index(op.f('ix_racing_payoffs_race_id'), table_name='payoffs', schema='racing')
    op.drop_table('payoffs', schema='racing')
    op.drop_index(op.f('ix_racing_races_meet_id'), table_name='races', schema='racing')
    op.drop_table('races', schema='racing')
    op.drop_index(op.f('ix_racing_meets_meet_id'), table_name='meets', schema='racing')
    op.drop_index(op.f('ix_racing_meets_date'), table_name='meets', schema='racing')
    op.drop_table('meets', schema='racing')
    op.drop_table('horse_owners', schema='racing')
    op.drop_index(op.f('ix_racing_trainers_last_name'), table_name='trainers', schema='racing')
    op.drop_index(op.f('ix_racing_trainers_api_id'), table_name='trainers', schema='racing')
    op.drop_table('trainers', schema='racing')
    op.drop_index(op.f('ix_racing_tracks_track_id'), table_name='tracks', schema='racing')
    op.drop_table('tracks', schema='racing')
    op.drop_index(op.f('ix_racing_owners_name'), table_name='owners', schema='racing')
    op.drop_table('owners', schema='racing')
    op.drop_index(op.f('ix_racing_jockeys_last_name'), table_name='jockeys', schema='racing')
    op.drop_index(op.f('ix_racing_jockeys_api_id'), table_name='jockeys', schema='racing')
    op.drop_table('jockeys', schema='racing')
    op.drop_index(op.f('ix_racing_horses_registration_number'), table_name='horses', schema='racing')
    op.drop_index(op.f('ix_racing_horses_name'), table_name='horses', schema='racing')
    op.drop_table('horses', schema='racing')
    # ### end Alembic commands ###
