package com.horseracing.api.controller;

import com.horseracing.api.service.PredictionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import lombok.extern.slf4j.Slf4j;
import java.util.Map;

@RestController
@RequestMapping("/api/predictions")
@CrossOrigin(origins = "*")
@Slf4j
@Tag(name = "Predictions", description = "ML-powered win probability predictions")
public class PredictionController {

    private final PredictionService predictionService;

    public PredictionController(PredictionService predictionService) {
        this.predictionService = predictionService;
    }

    @GetMapping("/health")
    @Operation(
            summary = "ML service health check",
            description = "Verifies the Flask ML microservice is running"
    )
    public ResponseEntity<Map<String, Object>> mlHealth() {
        boolean healthy = predictionService.isHealthy();
        return ResponseEntity.ok(Map.of(
                "ml_service_available", healthy,
                "status", healthy ? "connected" : "unavailable"
        ));
    }

    @GetMapping("/race/{raceId}")
    @Operation(
            summary = "Get win probability predictions for a race",
            description = """
            Returns ML model win probabilities for all runners in a race.
            
            Probabilities are generated by a Random Forest classifier
            trained on 1,300+ historical races with 55 features.
            
            Note: Currently uses morning line odds as primary signal.
            Full feature engineering integration coming soon.
            """
    )
    public ResponseEntity<Map<String, Object>> predictRace(
            @Parameter(description = "Race database ID", example = "502")
            @PathVariable Long raceId
    ) {
        try {
            Map<String, Object> predictions = predictionService.predictRace(raceId);
            return ResponseEntity.ok(predictions);
        } catch (Exception e) {
            log.error("Prediction failed for race {}: {}", raceId, e.getMessage());
            return ResponseEntity.internalServerError().body(Map.of(
                    "error", e.getMessage(),
                    "race_id", raceId
            ));
        }
    }
}